/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dtse1
 */
import db.employer;
import javax.swing.JOptionPane;
public class EmployerRegistration extends javax.swing.JFrame {

    /**
     * Creates new form EmployerRegistration
     */
    public EmployerRegistration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        firstnameLabel = new javax.swing.JLabel();
        lastnameLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        confirmpasswordLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        mobilenumberLabel = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        mobilenumber = new javax.swing.JTextField();
        signup = new javax.swing.JButton();
        gender = new javax.swing.JComboBox<>();
        password = new javax.swing.JPasswordField();
        confirmpassword = new javax.swing.JPasswordField();
        securityQuestion = new javax.swing.JComboBox<>();
        securityquestionLabel = new javax.swing.JLabel();
        emaiLabel = new javax.swing.JLabel();
        emai = new javax.swing.JTextField();
        backbtn = new javax.swing.JButton();
        answerlabel = new javax.swing.JLabel();
        answer = new javax.swing.JTextField();
        companyLabel = new javax.swing.JLabel();
        company = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employer Registeration Form ");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(204, 204, 255));
        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Registeration Form");
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(314, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 60));

        firstnameLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        firstnameLabel.setText("First Name ");
        firstnameLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(firstnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 210, 28));

        lastnameLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lastnameLabel.setText("Last Name");
        lastnameLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lastnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 210, 27));

        usernameLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        usernameLabel.setText("User Name");
        usernameLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 210, 26));

        passwordLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        passwordLabel.setText("Password");
        passwordLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 210, 28));

        confirmpasswordLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        confirmpasswordLabel.setText("Confirm Password");
        confirmpasswordLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(confirmpasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 210, 27));

        genderLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        genderLabel.setText("Gender");
        genderLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(genderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 210, 30));

        mobilenumberLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        mobilenumberLabel.setText("Mobile Number");
        mobilenumberLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(mobilenumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 210, 30));

        firstname.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        getContentPane().add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 372, 28));

        lastname.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        getContentPane().add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 372, -1));

        username.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 156, 372, 30));

        mobilenumber.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        mobilenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobilenumberActionPerformed(evt);
            }
        });
        getContentPane().add(mobilenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 372, -1));

        signup.setBackground(new java.awt.Color(204, 204, 255));
        signup.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        signup.setText("SignUp");
        signup.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        getContentPane().add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 570, 199, 41));

        gender.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 372, 30));

        password.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 372, -1));

        confirmpassword.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        getContentPane().add(confirmpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 370, -1));

        securityQuestion.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        securityQuestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Where was your father born?", "What is your eye color?", "What is your nick name?" }));
        securityQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securityQuestionActionPerformed(evt);
            }
        });
        getContentPane().add(securityQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 370, 30));

        securityquestionLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        securityquestionLabel.setText("Security Question");
        securityquestionLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(securityquestionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 210, 30));

        emaiLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        emaiLabel.setText("Email");
        emaiLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(emaiLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 210, 30));

        emai.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        emai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emaiActionPerformed(evt);
            }
        });
        getContentPane().add(emai, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 372, 30));

        backbtn.setBackground(new java.awt.Color(204, 204, 255));
        backbtn.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        backbtn.setText("Back");
        backbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        getContentPane().add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, 170, 40));

        answerlabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        answerlabel.setText("Answer");
        answerlabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(answerlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 210, 30));

        answer.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        getContentPane().add(answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 370, 30));

        companyLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        companyLabel.setText("Company");
        companyLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(companyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 210, 30));

        company.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        getContentPane().add(company, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, 372, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mobilenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobilenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobilenumberActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String fname = firstname.getText();
        String lname= lastname.getText();
        String uname= username.getText();
        String pass= password.getText();
        String cpass= confirmpassword.getText();
        String squestion= securityQuestion.getSelectedItem().toString();
        String ans = answer.getText();
        String gend = gender.getSelectedItem().toString();
        String mob = mobilenumber.getText();
        String mail= emai.getText();
        String com= company.getText();
        
        
        
        if(fname.equals("") || lname.equals("") || uname.equals("") || pass.equals("") 
                || cpass.equals("") || squestion.equals("") || ans.equals("") || mob.equals("") 
                || gend.equals("") || mail.equals("") || com.equals("") ){
        
                    JOptionPane.showMessageDialog(null, "All Fileds are required!!!");
        
        }else if (pass.equals(cpass)!=true){
            JOptionPane.showConfirmDialog(null, "passwords doesnt match!!!");
        }else{
            employer s = new employer();
            String query = "insert into users(firstname, lastname,username,password,securityquestion,answer,gender,phonenumber,email,cvlink,usertype) values( '"+
                    fname+"','"+lname+"','"+uname+"','"+pass+"','"+squestion+"','"+ans+"','"+gend+"',"+mob+",'"+mail+"','"+com+"','employer')";
            try{
            s.signup(query);
            JOptionPane.showMessageDialog(null, "Successfully Signed Up");
            setVisible(false);
            new Login().setVisible(true);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            
        }
        

    }//GEN-LAST:event_signupActionPerformed

    private void securityQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securityQuestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_securityQuestionActionPerformed

    private void emaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emaiActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        Login logout= new Login();
        logout.show();
        dispose();

    }//GEN-LAST:event_backbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployerRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answer;
    private javax.swing.JLabel answerlabel;
    private javax.swing.JButton backbtn;
    private javax.swing.JTextField company;
    private javax.swing.JLabel companyLabel;
    private javax.swing.JPasswordField confirmpassword;
    private javax.swing.JLabel confirmpasswordLabel;
    private javax.swing.JTextField emai;
    private javax.swing.JLabel emaiLabel;
    private javax.swing.JTextField firstname;
    private javax.swing.JLabel firstnameLabel;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastname;
    private javax.swing.JLabel lastnameLabel;
    private javax.swing.JTextField mobilenumber;
    private javax.swing.JLabel mobilenumberLabel;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JComboBox<String> securityQuestion;
    private javax.swing.JLabel securityquestionLabel;
    private javax.swing.JButton signup;
    private javax.swing.JTextField username;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
