/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dtse1
 */

import connection.connectionProvider;
import java.sql.*;
import db.seeker;
import db.employer;
import java.awt.Component;
import javax.swing.JOptionPane;


public class Login extends javax.swing.JFrame
{
        String usernameT;
        String passwordT;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setExtendedState(Login.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        msglable = new javax.swing.JLabel();
        usernameLable = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        passwordLable = new javax.swing.JLabel();
        identityLable = new javax.swing.JLabel();
        identity = new javax.swing.JComboBox<>();
        bthlogin = new javax.swing.JButton();
        btnsignin = new javax.swing.JButton();
        btnforget = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        msglable.setBackground(new java.awt.Color(153, 255, 255));
        msglable.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N

        usernameLable.setBackground(new java.awt.Color(204, 204, 255));
        usernameLable.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        usernameLable.setText("UserName");
        usernameLable.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        username.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        username.setToolTipText("");
        username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        password.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        passwordLable.setBackground(new java.awt.Color(204, 204, 255));
        passwordLable.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        passwordLable.setText("Password");
        passwordLable.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        identityLable.setBackground(new java.awt.Color(204, 204, 255));
        identityLable.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        identityLable.setText("Who are you?");
        identityLable.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        identity.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        identity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seeker", "Employer", "Admin" }));
        identity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        identity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(msglable, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(identityLable, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(passwordLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usernameLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(identity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(msglable, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordLable, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(identityLable, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(identity)))
        );

        usernameLable.getAccessibleContext().setAccessibleName("username");
        usernameLable.getAccessibleContext().setAccessibleDescription("");

        bthlogin.setBackground(new java.awt.Color(204, 204, 255));
        bthlogin.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        bthlogin.setText("Log in");
        bthlogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bthlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthloginActionPerformed(evt);
            }
        });

        btnsignin.setBackground(new java.awt.Color(204, 204, 255));
        btnsignin.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnsignin.setText("Create Account");
        btnsignin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsigninActionPerformed(evt);
            }
        });

        btnforget.setBackground(new java.awt.Color(204, 204, 255));
        btnforget.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnforget.setText("Forget Password");
        btnforget.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnforget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnforgetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bthlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129)
                        .addComponent(btnsignin, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(btnforget, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bthlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsignin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnforget, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void bthloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthloginActionPerformed
        // TODO add your handling code here:
        
        usernameT = username.getText();
        passwordT = password.getText();
        String id = identity.getSelectedItem().toString();
        String query = "select * from users where username='"+usernameT+"'and password='"+passwordT+"'";
        if(passwordT.equals("") || usernameT.equals("")){
                JOptionPane.showMessageDialog(null, "ALL FIELDS ARE REQUIRED!!!");
        }else if(passwordT.equals("admin") && usernameT.equals("admin")){
                
                Connection conn = connectionProvider.getCon();
                try{
                Statement stmt = conn.createStatement();
                ResultSet res = stmt.executeQuery(query);
                setVisible(false);
                
                res.next();
                new Admin(res).setVisible(true);
                }catch(Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage());
                }
        }else{
            seeker s = new seeker();
            employer e = new employer();
            ResultSet res = null;
            if(id.equals("Seeker")){
                query = "select * from users where usertype='seeker' and username='"+usernameT+"'and password='"+passwordT+"'";
                try{
                    Connection conn = connectionProvider.getCon();
                    Statement stmt = conn.createStatement();
                    res = stmt.executeQuery(query);
                if(res.next()){
                    
                    setVisible(false);
                    new JobSeeker(res).setVisible(true);

                }else{
                    JOptionPane.showMessageDialog(null, "INCORRECT PASSOWRD OR USERNAME!!!" );
            
            
            }}catch(Exception exec){
                JOptionPane.showMessageDialog(null, exec.getMessage());
            }
            }
            else{
                query = "select * from users where usertyp = 'employer' and username='"+usernameT+"'and password='"+passwordT+"'";
                res = e.login(usernameT, passwordT);
                try{
                if(res.next()){
                    setVisible(false);
                    new Employer(res).setVisible(true);

                }else{
                    JOptionPane.showMessageDialog(null, "INCORRECT PASSOWRD OR USERNAME!!!" );
            
            
            }}catch(Exception exec){
                JOptionPane.showMessageDialog(null, exec.getMessage());
            }
            
            
            }
            
            
        }
        
        
        
        
        
        
    }//GEN-LAST:event_bthloginActionPerformed

    private void btnsigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsigninActionPerformed
        // TODO add your handling code here:
        CreateAccount acc= new  CreateAccount();
        acc.show();
        dispose();
    }//GEN-LAST:event_btnsigninActionPerformed

    private void btnforgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnforgetActionPerformed
        // TODO add your handling code here:
        ForgetPassword pass= new ForgetPassword();
        pass.show();
        dispose();
    }//GEN-LAST:event_btnforgetActionPerformed

    private void identityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bthlogin;
    private javax.swing.JButton btnforget;
    private javax.swing.JButton btnsignin;
    private javax.swing.JComboBox<String> identity;
    private javax.swing.JLabel identityLable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel msglable;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordLable;
    private javax.swing.JTextField username;
    private javax.swing.JLabel usernameLable;
    // End of variables declaration//GEN-END:variables
}
