
import javax.swing.JOptionPane;
import db.seeker;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dtse1
 */


public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstnameLable = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lastnameLable = new javax.swing.JLabel();
        usernameLable = new javax.swing.JLabel();
        passwordLable = new javax.swing.JLabel();
        confirmpasswordLable = new javax.swing.JLabel();
        genderLable = new javax.swing.JLabel();
        mobilenumberLable = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        mobilenumber = new javax.swing.JTextField();
        signup = new javax.swing.JButton();
        gender = new javax.swing.JComboBox<>();
        password = new javax.swing.JPasswordField();
        confirmpassword = new javax.swing.JPasswordField();
        securityQuestion = new javax.swing.JComboBox<>();
        securityQuestionLable = new javax.swing.JLabel();
        emailLable = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        backbtn = new javax.swing.JButton();
        answerLable = new javax.swing.JLabel();
        answer = new javax.swing.JTextField();
        successmsg = new javax.swing.JLabel();
        cvlinkLable = new javax.swing.JLabel();
        cvlink = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("registerframe");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstnameLable.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        firstnameLable.setText("First Name ");
        firstnameLable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(firstnameLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 53, 181, 28));

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel9.setText("Registeration Form");
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 737, 50));

        lastnameLable.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lastnameLable.setText("Last Name");
        lastnameLable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lastnameLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 93, 181, 27));

        usernameLable.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        usernameLable.setText("User Name");
        usernameLable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(usernameLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 126, 181, 26));

        passwordLable.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        passwordLable.setText("Password");
        passwordLable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(passwordLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 181, 28));

        confirmpasswordLable.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        confirmpasswordLable.setText("Confirm Password");
        confirmpasswordLable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(confirmpasswordLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 181, 27));

        genderLable.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        genderLable.setText("Gender");
        genderLable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(genderLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 181, 30));

        mobilenumberLable.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        mobilenumberLable.setText("Mobile Number");
        mobilenumberLable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(mobilenumberLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 181, 30));

        firstname.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        firstname.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 53, 372, 28));

        lastname.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lastname.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 93, 372, -1));

        username.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        username.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 126, 372, 26));

        mobilenumber.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        mobilenumber.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mobilenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobilenumberActionPerformed(evt);
            }
        });
        getContentPane().add(mobilenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 372, -1));

        signup.setBackground(new java.awt.Color(204, 204, 255));
        signup.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        signup.setText("SignUp");
        signup.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        getContentPane().add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 540, 199, 41));

        gender.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        gender.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 372, 30));

        password.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        password.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 164, 372, -1));

        confirmpassword.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        confirmpassword.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(confirmpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 201, 372, -1));

        securityQuestion.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        securityQuestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Where was your father born?", "What is your eye color?", "What is your nick name?" }));
        securityQuestion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        securityQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securityQuestionActionPerformed(evt);
            }
        });
        getContentPane().add(securityQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 370, 30));

        securityQuestionLable.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        securityQuestionLable.setText("Security Question");
        securityQuestionLable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(securityQuestionLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 180, 30));

        emailLable.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        emailLable.setText("Email");
        emailLable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(emailLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 180, 30));

        email.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        email.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 370, 30));

        backbtn.setBackground(new java.awt.Color(204, 204, 255));
        backbtn.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        backbtn.setText("Back");
        backbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        getContentPane().add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 170, 40));

        answerLable.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        answerLable.setText("Answer");
        answerLable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(answerLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 180, 30));

        answer.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        answer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 302, 370, 30));
        getContentPane().add(successmsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 580, 460, 60));

        cvlinkLable.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        cvlinkLable.setText("CV link");
        cvlinkLable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(cvlinkLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 180, 30));

        cvlink.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        cvlink.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(cvlink, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 370, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mobilenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobilenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobilenumberActionPerformed

    private void securityQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securityQuestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_securityQuestionActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        Login logout= new Login();
        logout.show();
        dispose();
        
    }//GEN-LAST:event_backbtnActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        // TODO add your handling code here:
        String fname = firstname.getText();
        String lname= lastname.getText();
        String uname= username.getText();
        String pass= password.getText();
        String cpass= confirmpassword.getText();
        String squestion= securityQuestion.getSelectedItem().toString();
        String ans = answer.getText();
        String gend = gender.getSelectedItem().toString();
        String mob = mobilenumber.getText();
        String mail= email.getText();
        String cv= cvlink.getText();
        
        
        
        if(fname.equals("") || lname.equals("") || uname.equals("") || pass.equals("") 
                || cpass.equals("") || squestion.equals("") || ans.equals("") || mob.equals("") 
                || gend.equals("") || mail.equals("") || cv.equals("") ){
        
                    JOptionPane.showMessageDialog(null, "All Fileds are required!!!");
        
        }else if (pass.equals(cpass)!=true){
            JOptionPane.showConfirmDialog(null, "passwords doesnt match!!!");
        }else{
            seeker s = new seeker();
            String query = "insert into users(firstname, lastname,username,password,securityquestion,answer,gender,phonenumber,email,cvlink,usertype) values( '"+
                    fname+"','"+lname+"','"+uname+"','"+pass+"','"+squestion+"','"+ans+"','"+gend+"',"+mob+",'"+mail+"','"+cv+"','seeker')";
            try{
            s.signup(query);
            JOptionPane.showMessageDialog(null, "Successfully Signed Up");
            setVisible(false);
            new Login().setVisible(true);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            
        }
        
        
        
    }//GEN-LAST:event_signupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answer;
    private javax.swing.JLabel answerLable;
    private javax.swing.JButton backbtn;
    private javax.swing.JPasswordField confirmpassword;
    private javax.swing.JLabel confirmpasswordLable;
    private javax.swing.JTextField cvlink;
    private javax.swing.JLabel cvlinkLable;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailLable;
    private javax.swing.JTextField firstname;
    private javax.swing.JLabel firstnameLable;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel genderLable;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastname;
    private javax.swing.JLabel lastnameLable;
    private javax.swing.JTextField mobilenumber;
    private javax.swing.JLabel mobilenumberLable;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordLable;
    private javax.swing.JComboBox<String> securityQuestion;
    private javax.swing.JLabel securityQuestionLable;
    private javax.swing.JButton signup;
    private javax.swing.JLabel successmsg;
    private javax.swing.JTextField username;
    private javax.swing.JLabel usernameLable;
    // End of variables declaration//GEN-END:variables
}
